
import { Taunt, TauntCategory } from './types';

export const TAUNTS: Taunt[] = [
  { id: 1, text: "Yes.", category: TauntCategory.ESSENTIAL },
  { id: 2, text: "No.", category: TauntCategory.ESSENTIAL },
  { id: 3, text: "Good luck, have fun.", category: TauntCategory.ESSENTIAL },
  { id: 4, text: "Are you ready to battle?", category: TauntCategory.ESSENTIAL },
  { id: 5, text: "Oh, oh, I can't wait!", category: TauntCategory.FLAVOR },
  { id: 6, text: "The anticipation is killing me.", category: TauntCategory.FLAVOR },
  { id: 7, text: "Ding ding!", category: TauntCategory.FLAVOR },
  { id: 8, text: "All hail, king of the losers!", category: TauntCategory.FLAVOR },
  { id: 9, text: "Oooohhhh!", category: TauntCategory.FLAVOR },
  { id: 10, text: "Hey, I'm in your town.", category: TauntCategory.INTEL },
  { id: 11, text: "Group laugh", category: TauntCategory.FLAVOR },
  { id: 12, text: "Ah! Being rushed.", category: TauntCategory.INTEL },
  { id: 13, text: "Group Cheer", category: TauntCategory.FLAVOR },
  { id: 14, text: "Start the game already!", category: TauntCategory.ESSENTIAL },
  { id: 15, text: "Are you still there?", category: TauntCategory.ESSENTIAL },
  { id: 16, text: "Not like this! Not like this!", category: TauntCategory.FLAVOR },
  { id: 17, text: "Crickets", category: TauntCategory.FLAVOR },
  { id: 18, text: "Group Wince", category: TauntCategory.FLAVOR },
  { id: 19, text: "Sure, blame it on your ISP.", category: TauntCategory.FLAVOR },
  { id: 20, text: "Don't point that thing at me!", category: TauntCategory.FLAVOR },
  { id: 21, text: "I'm in your base, killing your units.", category: TauntCategory.INTEL },
  { id: 22, text: "It is good to be the king.", category: TauntCategory.FLAVOR },
  { id: 23, text: "I am weak! Please don't kill me!", category: TauntCategory.FLAVOR },
  { id: 24, text: "How could you do this to me?", category: TauntCategory.FLAVOR },
  { id: 25, text: "Long time, no siege.", category: TauntCategory.FLAVOR },
  { id: 26, text: "I just got some ...satisfaction!", category: TauntCategory.FLAVOR },
  { id: 27, text: "Nice town, I'll take it.", category: TauntCategory.FLAVOR },
  { id: 28, text: "I ...did not expect that.", category: TauntCategory.FLAVOR },
  { id: 29, text: "Quit bothering me!", category: TauntCategory.FLAVOR },
  { id: 30, text: "Raiding party!", category: TauntCategory.COMBAT },
  { id: 31, text: "I'll take that trade.", category: TauntCategory.ESSENTIAL },
  { id: 32, text: "Eh, smite me.", category: TauntCategory.FLAVOR },
  { id: 33, text: "Can you believe it?", category: TauntCategory.FLAVOR },
  { id: 34, text: "The wonder, the wonder, the ...no!", category: TauntCategory.FLAVOR },
  { id: 35, text: "What a play!", category: TauntCategory.FLAVOR },
  { id: 36, text: "You played two hours to die like this?", category: TauntCategory.FLAVOR },
  { id: 37, text: "Yeah, well, you should see the other guy.", category: TauntCategory.FLAVOR },
  { id: 38, text: "Roggan.", category: TauntCategory.FLAVOR },
  { id: 39, text: "Wololo.", category: TauntCategory.FLAVOR },
  { id: 40, text: "Good game, well played.", category: TauntCategory.ESSENTIAL },
  { id: 41, text: "GG, no re!", category: TauntCategory.ESSENTIAL },
  { id: 42, text: "GG, re?", category: TauntCategory.ESSENTIAL },
  { id: 43, text: "Food please.", category: TauntCategory.ESSENTIAL },
  { id: 44, text: "Wood please.", category: TauntCategory.ESSENTIAL },
  { id: 45, text: "Gold please.", category: TauntCategory.ESSENTIAL },
  { id: 46, text: "Stone please.", category: TauntCategory.ESSENTIAL },
  { id: 47, text: "Send me your extra resources!", category: TauntCategory.ESSENTIAL },
  { id: 48, text: "Let's go for a Conquest victory.", category: TauntCategory.COMBAT },
  { id: 49, text: "Let's go for a Sacred victory.", category: TauntCategory.COMBAT },
  { id: 50, text: "Let's go for a Wonder victory.", category: TauntCategory.COMBAT },
  { id: 51, text: "I'm capturing a Sacred Site!", category: TauntCategory.INTEL },
  { id: 52, text: "Defend our Sacred Site!", category: TauntCategory.COMBAT },
  { id: 53, text: "I'm building a Wonder!", category: TauntCategory.INTEL },
  { id: 54, text: "Protect my Wonder!", category: TauntCategory.COMBAT },
  { id: 55, text: "Enemy is preparing to rush.", category: TauntCategory.INTEL },
  { id: 56, text: "Enemy is building defences.", category: TauntCategory.INTEL },
  { id: 57, text: "Enemy is booming.", category: TauntCategory.INTEL },
  { id: 58, text: "Enemy has a trade route.", category: TauntCategory.INTEL },
  { id: 59, text: "Let's move in together.", category: TauntCategory.COMBAT },
  { id: 60, text: "Wait, I'm not ready yet.", category: TauntCategory.ESSENTIAL },
  { id: 61, text: "I need more time.", category: TauntCategory.ESSENTIAL },
  { id: 62, text: "Fight alongside me!", category: TauntCategory.COMBAT },
  { id: 63, text: "I'm under attack!", category: TauntCategory.INTEL },
  { id: 64, text: "Hold the line!", category: TauntCategory.COMBAT },
  { id: 65, text: "Don't give them any ground!", category: TauntCategory.COMBAT },
  { id: 66, text: "Watch out for the enemy infantry!", category: TauntCategory.INTEL },
  { id: 67, text: "Watch out for the enemy cavalry!", category: TauntCategory.INTEL },
  { id: 68, text: "Watch out for the enemy ranged units!", category: TauntCategory.INTEL },
  { id: 69, text: "Watch out for the enemy enemy ships!", category: TauntCategory.INTEL },
  { id: 70, text: "Watch out for the enemy enemy siege!", category: TauntCategory.INTEL },
  { id: 71, text: "I'm scouting the enemy.", category: TauntCategory.INTEL },
  { id: 72, text: "Can you scout the enemy?", category: TauntCategory.INTEL },
  { id: 73, text: "Enemy Scout heading your way.", category: TauntCategory.INTEL },
  { id: 74, text: "Build infantry.", category: TauntCategory.COMBAT },
  { id: 75, text: "Build cavalry.", category: TauntCategory.COMBAT },
  { id: 76, text: "Build ranged units.", category: TauntCategory.COMBAT },
  { id: 77, text: "Build a navy.", category: TauntCategory.COMBAT },
  { id: 78, text: "Build siege.", category: TauntCategory.COMBAT },
  { id: 79, text: "Build forces to repel enemy infantry!", category: TauntCategory.COMBAT },
  { id: 80, text: "Build forces to repel enemy cavalry!", category: TauntCategory.COMBAT },
  { id: 81, text: "Build forces to repel enemy ranged units!", category: TauntCategory.COMBAT },
  { id: 82, text: "Build forces to repel enemy ships!", category: TauntCategory.COMBAT },
  { id: 83, text: "Build forces to repel enemy enemy siege!", category: TauntCategory.COMBAT },
  { id: 84, text: "Attack the Blue player!", category: TauntCategory.PLAYERS, color: "blue" },
  { id: 85, text: "Attack the Red player!", category: TauntCategory.PLAYERS, color: "red" },
  { id: 86, text: "Attack the Yellow player!", category: TauntCategory.PLAYERS, color: "yellow" },
  { id: 87, text: "Attack the Green player!", category: TauntCategory.PLAYERS, color: "green" },
  { id: 88, text: "Attack the Teal player!", category: TauntCategory.PLAYERS, color: "teal" },
  { id: 89, text: "Attack the Purple player!", category: TauntCategory.PLAYERS, color: "purple" },
  { id: 90, text: "Attack the Orange player!", category: TauntCategory.PLAYERS, color: "orange" },
  { id: 91, text: "Attack the Pink player!", category: TauntCategory.PLAYERS, color: "pink" },
  { id: 92, text: "Defend the Blue player!", category: TauntCategory.PLAYERS, color: "blue" },
  { id: 93, text: "Defend the Red player!", category: TauntCategory.PLAYERS, color: "red" },
  { id: 94, text: "Defend the Yellow player!", category: TauntCategory.PLAYERS, color: "yellow" },
  { id: 95, text: "Defend the Green player!", category: TauntCategory.PLAYERS, color: "green" },
  { id: 96, text: "Defend the Teal player!", category: TauntCategory.PLAYERS, color: "teal" },
  { id: 97, text: "Defend the Purple player!", category: TauntCategory.PLAYERS, color: "purple" },
  { id: 98, text: "Defend the Orange player!", category: TauntCategory.PLAYERS, color: "orange" },
  { id: 99, text: "Defend the Pink player!", category: TauntCategory.PLAYERS, color: "pink" },
  { id: 100, text: "Retreat! Retreat!", category: TauntCategory.ESSENTIAL },
  { id: 101, text: "Build walls here!", category: TauntCategory.COMBAT },
  { id: 102, text: "Please delete this wall.", category: TauntCategory.COMBAT },
  { id: 103, text: "Let's build here!", category: TauntCategory.COMBAT },
  { id: 104, text: "Please delete this building.", category: TauntCategory.COMBAT },
  { id: 105, text: "OP.", category: TauntCategory.FLAVOR },
  { id: 106, text: "Nice sheep.", category: TauntCategory.FLAVOR },
  { id: 107, text: "Remember when you had an army?", category: TauntCategory.FLAVOR },
  { id: 108, text: "Well that escalated quickly.", category: TauntCategory.FLAVOR },
  { id: 109, text: "STRAEEELBOOORRAAAA!", category: TauntCategory.FLAVOR },
  { id: 110, text: "Behold! My amazing army!", category: TauntCategory.FLAVOR },
  { id: 111, text: "This is fine...", category: TauntCategory.FLAVOR },
  { id: 112, text: "You know, this game has a good tutorial.", category: TauntCategory.FLAVOR },
  { id: 113, text: "It has been a pleasure.", category: TauntCategory.ESSENTIAL },
  { id: 114, text: "I ...did not see that coming.", category: TauntCategory.FLAVOR },
];
